[rewrite]
^https:\/\/www\.ecosia\.org\/search\?q=dd\+([^&]+) url 307 https://duckduckgo.com/?q=$1
^https:\/\/www\.ecosia\.org\/search\?q=([^&]+) url 307 https://www.google.com/search?q=$1

[mitm]
hostname = *.ecosia.org
