#!name=Ecosia Search Redirect
#!desc=Safari 默认搜索引擎为 Ecosia 时，dd 关键字跳转 DuckDuckGo，其余搜索跳转 Google
#!author=CHEN1016

[rewrite]
^https:\/\/www\.ecosia\.org\/search\?q=dd\+([^&]+) url 307 https://duckduckgo.com/?q=$1
^https:\/\/www\.ecosia\.org\/search\?q=([^&]+) url 307 https://www.google.com/search?q=$1

[mitm]
hostname = *.ecosia.org
